#!/usr/bin/env node
/**
 * Builds the deployable site into dist/ and writes config.js from environment
 * variables (SUPABASE_URL, SUPABASE_ANON_KEY), falling back to a .env file.
 * No bundler: the app is plain HTML/CSS/JS, so this only copies files.
 *
 *   node scripts/build.js            -> dist/
 *   node scripts/build.js --local    -> overwrites ./config.js for `./serve.sh` (the anon key is a public value)
 */
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');

function loadDotEnv() {
  const p = path.join(root, '.env');
  if (!fs.existsSync(p)) return;
  for (const line of fs.readFileSync(p, 'utf8').split('\n')) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (m && process.env[m[1]] === undefined) process.env[m[1]] = m[2].replace(/^["']|["']$/g, '');
  }
}
loadDotEnv();
const url = process.env.SUPABASE_URL || '';
const key = process.env.SUPABASE_ANON_KEY || '';
const config = `// Generated by scripts/build.js. Do not edit; set SUPABASE_URL and SUPABASE_ANON_KEY instead.\nwindow.READER_CONFIG = ${JSON.stringify({ supabaseUrl: url, supabaseAnonKey: key }, null, 2)};\n`;

if (process.argv.includes('--local')) {
  fs.writeFileSync(path.join(root, 'config.js'), config);
  console.log(`Wrote config.js (${url ? 'cloud mode: ' + url : 'per-browser mode, no Supabase configured'})`);
  process.exit(0);
}

const dist = path.join(root, 'dist');
fs.rmSync(dist, { recursive: true, force: true });
fs.mkdirSync(dist, { recursive: true });
for (const entry of ['index.html', 'css', 'js']) {
  fs.cpSync(path.join(root, entry), path.join(dist, entry), { recursive: true });
}
fs.writeFileSync(path.join(dist, 'config.js'), config);
fs.writeFileSync(path.join(dist, '.nojekyll'), '');
console.log(`Built dist/ (${url ? 'cloud mode: ' + url : 'per-browser mode, no Supabase configured'})`);
if (!url || !key) console.warn('Warning: SUPABASE_URL / SUPABASE_ANON_KEY not set. The site will store books in each browser only.');
